model_params:
  name: 'pm4'
  hidden: 512
  n_layers: 12
  attn_heads: 8
  dropout: 0.1
  epoch: 200

data_params:
  data_path: "ml_dataset/pm-dataset-cleaned-indexed.parquet"
  tokenizer_path: "ml_dataset/tokenizer.json"
  train_batch_size: 128
  val_batch_size:  128
  num_workers: 20
  
exp_params:
  LR: 0.0001
  weight_decay: 0

