model_params:
  name: 'transformer-vae'
  max_seq_len: 30
  in_channels: 3
  latent_dim: 128
  loss_type: 'B'
  gamma: 10.0
  max_capacity: 25
  Capacity_max_iter: 10000

data_params:
  data_path: "ml_dataset/pm-dataset-indexed.parquet"
  tokenizer_path: "ml_dataset/tokenizer.json"
  train_batch_size: 128
  val_batch_size:  32
  num_workers: 20
  
exp_params:
  LR: 0.005
  weight_decay: 0.0001
  scheduler_gamma: 0.95
  kld_weight: 0.00025
  manual_seed: 1265
