model_params:
  name: 'pm'
  hidden: 384
  n_layers: 3
  attn_heads: 6
  dropout: 0

data_params:
  data_path: "ml_dataset/pm-dataset-cleaned-indexed.parquet"
  tokenizer_path: "ml_dataset/tokenizer.json"
  train_batch_size: 64
  val_batch_size:  64
  num_workers: 20
  
exp_params:
  LR: 0.00002
  weight_decay: 0

